
package com.netsuite.webservices.v2016_2.platform;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-02-06T17:32:15.879+02:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "unexpectedErrorFault", targetNamespace = "urn:faults_2016_2.platform.webservices.netsuite.com")
public class UnexpectedErrorFault extends Exception {
    
    private com.netsuite.webservices.v2016_2.platform.faults.UnexpectedErrorFault unexpectedErrorFault;

    public UnexpectedErrorFault() {
        super();
    }
    
    public UnexpectedErrorFault(String message) {
        super(message);
    }
    
    public UnexpectedErrorFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnexpectedErrorFault(String message, com.netsuite.webservices.v2016_2.platform.faults.UnexpectedErrorFault unexpectedErrorFault) {
        super(message);
        this.unexpectedErrorFault = unexpectedErrorFault;
    }

    public UnexpectedErrorFault(String message, com.netsuite.webservices.v2016_2.platform.faults.UnexpectedErrorFault unexpectedErrorFault, Throwable cause) {
        super(message, cause);
        this.unexpectedErrorFault = unexpectedErrorFault;
    }

    public com.netsuite.webservices.v2016_2.platform.faults.UnexpectedErrorFault getFaultInfo() {
        return this.unexpectedErrorFault;
    }
}
